### PR TITLE
Handle empty subject

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by wagnerand** [comment]
@Osmose *ping*

**Comment by Osmose** [comment]
Oh hey, guess who didn't ever set himself to watch the repo?

My bad.

**Review by Osmose — APPROVED** [review]

**Comment by Osmose** [comment]
Tagged in https://github.com/Osmose/mailman-admin-helper/releases/tag/v0.1.7. XPI should be up there soon. Thanks!

**Comment by wagnerand** [comment]
Thanks!

**Pull request merged**
